[package]
name = "lude-simul"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Entity-Component-System"
license = "MIT OR Apache-2.0"

[dependencies]
clone = "0.1.1"
idem = "0.1"
tempus = { version = "0.2.1", features = ["libc"] }
